export default {
    normal: require('../assets/type_imgs/normal.png'),
    fighting: require('../assets/type_imgs/fighting.png'),
    flying: require('../assets/type_imgs/flying.png'),
    poison: require('../assets/type_imgs/poison.png'),
    ground: require('../assets/type_imgs/ground.png'),
    rock: require('../assets/type_imgs/rock.png'),
    bug: require('../assets/type_imgs/bug.png'),
    ghost: require('../assets/type_imgs/ghost.png'),
    steel: require('../assets/type_imgs/stell.png'),
    fire: require('../assets/type_imgs/fire.png'),
    water: require('../assets/type_imgs/water.png'),
    grass: require('../assets/type_imgs/grass.png'),
    electric: require('../assets/type_imgs/electric.png'),
    psychic: require('../assets/type_imgs/psychic.png'),
    ice: require('../assets/type_imgs/ice.png'),
    dragon: require('../assets/type_imgs/dragon.png'),
    dark: require('../assets/type_imgs/dark.png'),
    fairy: require('../assets/type_imgs/fairy.png'),
    unknown: require('../assets/type_imgs/poke-black-ball.jpg'),
    shadow: require('../assets/type_imgs/poke-black-ball.jpg'),
}